name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Установка зависимостей
        run: npm install

      - name: Сборка проекта
        run: npm run build

      - name: Настройка Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Вход в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Сборка и отправка образа Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/quackjs-frontend
           

      

  
  deploy-prod-1:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Настройка SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}

      - name: Деплой на PROD сервер 1
        run: |
          ssh -o StrictHostKeyChecking=no user1@${{ secrets.PROD_SERVER_IP }} << 'EOF'
            set -e
            echo "✅ Подключение к PROD серверу 1"
            cd ??? || exit 1

            echo "📦 Pull образов"
            kubectl delete -f quackjs-deployment.yaml -n web
            kubectl apply -f quackjs-deployment.yaml -n web
            echo "✅ Деплой PROD #1 завершён"
          EOF

